config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root controller: :welcome, action: :index
  resource :hello, only: [:create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hellos_controller.rb
class HellosController < ActionController::Base
  def create
    data = { time: Time.current, ip: request.remote_ip }
    data[:message] = ERB::Util.html_escape(params[:message]) if params[:message].present?
    ActionCable.server.broadcast 'hello_messages', data
    head :ok
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  layout 'application'

  def index; end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample Rails App</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <section>
    <p>
      <a href="http://rubyonrails.org">
        <img width="130" height="46" alt="Ruby on Rails" border="0" src="<%= image_path 'rails.svg' %>" />
      </a>
    </p>

    <h1>Yay! You&rsquo;re on Rails!</h1>

    <img alt="Welcome" class="welcome" src="<%= image_path 'welcome.jpg' %>" />

    <p class="version">
      <strong>Rails version:</strong> <%= Rails.version %><br />
      <strong>Ruby version:</strong> <%= RUBY_VERSION %> (<%= RUBY_PLATFORM %>)
    </p>

    <div class="hello">
      <strong>Say hello:</strong>
      <%= form_tag hello_path, remote: true do %>
        <%= text_field_tag :message, 'Hello', placeholder: 'Enter hello message' %>
        <%= submit_tag 'Send' %>
      <% end %>
      <p id="messages">
        <strong id="messages-title">Recieved hello messages (<span id="messages-sataus">not connected</span>):<br/></strong>
        <span id="messages-placeholder">No messages yet</span>
      </p>
    </div>
  </section>
</div>